# Generated by Django 5.0.2 on 2024-04-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_clicker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
